version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - '3274:80'
    env_file:
      - ./.env
    volumes:
      - database:/var/www/html/database
    restart: unless-stopped

volumes:
  database: {}
