services:
  api:
    image: php:7-apache
    ports:
      - '3274:80'
    env_file:
      - ./.env
      - ./.env.development.local
    volumes:
      - ./public/api:/var/www/html/api
      - database:/var/www/html/database
  sqlite-web:
    image: coleifer/sqlite-web
    ports:
      - '8080:8080'
    volumes:
      - database:/data
      - ./assets/db/:/db
    entrypoint: sh -c "/db/migrate.sh /data/development.db /db/migrations && sqlite_web -H 0.0.0.0 -x development.db"
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      tags:
        - 54ac/openwebscrobbler:php7
        - 54ac/openwebscrobbler:latest
    ports:
      - '3274:80'
    env_file:
      - ./.env
    volumes:
      - database:/var/www/html/database
    restart: unless-stopped

volumes:
  database: {}
